# Generated by Django 4.2.7 on 2026-07-21 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("passenger_name", models.CharField(max_length=200)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        default="credit",
                        max_length=10,
                    ),
                ),
                ("amount_pkr", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("outstanding", "Outstanding"), ("paid", "Paid")],
                        default="outstanding",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_entries",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="vendor_ledg_status_5c0268_idx"
                    ),
                    models.Index(
                        fields=["passenger_name"], name="vendor_ledg_passeng_721dc1_idx"
                    ),
                ],
            },
        ),
    ]
