# Generated by Django 4.2.7 on 2026-07-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("vendor_ledger", "0002_alter_vendorledgerentry_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorledgerentry",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="accounts.vendor",
            ),
        ),
    ]
