# Generated by Django 4.2.7 on 2026-07-21 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("passenger_name", models.CharField(max_length=200)),
                ("passport_no", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "pnr",
                    models.CharField(blank=True, max_length=50, verbose_name="PNR"),
                ),
                ("flight_date", models.DateField(blank=True, null=True)),
                ("airline", models.CharField(blank=True, max_length=100)),
                (
                    "vendor_cost_pkr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Vendor Cost in PKR — what we owe the vendor",
                        max_digits=12,
                    ),
                ),
                (
                    "ticket_price_pkr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ticket Price in PKR — what the customer pays us",
                        max_digits=12,
                    ),
                ),
                (
                    "profit_pkr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-calculated: Ticket Price - Vendor Cost",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["passenger_name"], name="tickets_passeng_dfbbc1_idx"
                    ),
                    models.Index(
                        fields=["passport_no"], name="tickets_passpor_0024c0_idx"
                    ),
                    models.Index(fields=["status"], name="tickets_status_fbbf05_idx"),
                    models.Index(fields=["pnr"], name="tickets_pnr_5a14b7_idx"),
                    models.Index(
                        fields=["created_at"], name="tickets_created_ed60df_idx"
                    ),
                ],
            },
        ),
    ]
