# Generated by Django 4.2.7 on 2026-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_customer_ticket_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("flight", "Flight Ticket"),
                    ("visa", "Visa"),
                    ("umrah", "Umrah"),
                ],
                default="flight",
                max_length=10,
            ),
        ),
    ]
