# Generated by Django 4.2.7 on 2026-08-13 12:11

from django.db import migrations, models


def pending_to_confirmed(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    Ticket.objects.filter(status='pending').update(status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="country",
            field=models.CharField(
                blank=True, help_text="Visa country", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="madina_hotel",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="ticket",
            name="makkah_hotel",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="ticket",
            name="package",
            field=models.CharField(
                blank=True,
                choices=[("star", "Star"), ("economy", "Economy")],
                help_text="Umrah package",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sector",
            field=models.CharField(
                blank=True, help_text="Flight sector e.g. KHI-JED", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="stay_date",
            field=models.DateField(blank=True, help_text="Umrah stay date", null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="visa_type",
            field=models.CharField(
                blank=True,
                choices=[("visit", "Visit"), ("work", "Work"), ("student", "Student")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.RunPython(pending_to_confirmed, migrations.RunPython.noop),
    ]
