# Generated by Django 4.2.7 on 2026-07-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
        ("customer_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerledgerentry",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_entries",
                to="tickets.ticket",
            ),
        ),
    ]
