# Generated by Django 4.2.7 on 2026-08-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
        ("customer_ledger", "0003_customerledgerentry_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerledgerentry",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bank.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="advance_option",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="amount_sar",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="branch",
            field=models.CharField(blank=True, default="Lahore", max_length=100),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="cash_flow",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="invoice_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="payment_method",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="voucher_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="voucher_status",
            field=models.CharField(default="final", max_length=20),
        ),
    ]
